name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet 
      uses: actions/setup-dotnet@v2
    - name: Display dotnet version
      run: dotnet --version
    - name: adding nuget source 
      run : dotnet nuget add source --username karanbajaj --password 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 --store-password-in-clear-text --name github2 "https://nuget.pkg.github.com/STRIKE-HEALTH/index.json"
    - name: package packageSources
      run: dotnet nuget list source 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
