name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '6.0.x' ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet 
      uses: actions/setup-dotnet@v2
    - name: Install dependencies
      run: dotnet add package Newtonsoft.Json --version 12.0.1
    - name: Display dotnet version
      run: dotnet --version
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
